services:
#Django App
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - django_redis

  #redis
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - 6379:6379

  